/**
 * Sync the live event state into the agent workspace.
 *
 * Writes four files (idempotent, each overwritten on every sync):
 *   current-state.json — authoritative live state, JSON
 *   guests.csv         — guest list, human-readable
 *   tables.md          — current seating per table, human-readable
 *   constraints.md     — must / must-not constraints, human-readable
 */

import fs from "node:fs/promises";
import type { EventState, SeatKey } from "../types";
import { parseSeatKey } from "../types";
import { workspacePaths } from "./paths";

export interface SyncInput {
  /** Workspace root absolute path. */
  root: string;
  /** Subset of EventState we actually need to render. */
  state: Pick<EventState, "id" | "name" | "guests" | "tables" | "assignments" | "constraints">;
}

export async function syncWorkspace({ root, state }: SyncInput): Promise<void> {
  const p = workspacePaths(root);

  await Promise.all([
    fs.writeFile(p.currentState, renderCurrentStateJSON(state), "utf8"),
    fs.writeFile(p.guestsCsv, renderGuestsCSV(state), "utf8"),
    fs.writeFile(p.tablesMd, renderTablesMD(state), "utf8"),
    fs.writeFile(p.constraintsMd, renderConstraintsMD(state), "utf8"),
  ]);
}

// ---------------------------------------------------------------------------
// Renderers
// ---------------------------------------------------------------------------

function renderCurrentStateJSON(s: SyncInput["state"]): string {
  const seatedGuestIds = new Set(Object.values(s.assignments));

  const tables = s.tables.map((t) => {
    const seats = Array.from({ length: t.capacity }, (_, i) => {
      const key: SeatKey = `${t.id}:${i}`;
      const guestId = s.assignments[key] ?? null;
      return { index: i, guestId, locked: false };
    });
    return {
      id: t.id,
      label: t.label,
      shape: t.shape,
      seatCount: t.capacity,
      seats,
    };
  });

  const guests = s.guests.map((g) => {
    const seatKey = Object.entries(s.assignments).find(([, v]) => v === g.id)?.[0];
    const seat = seatKey ? parseSeatKey(seatKey) : null;
    const table = seat ? s.tables.find((t) => t.id === seat.tableId) : null;
    return {
      id: g.id,
      name: g.name,
      affiliation: g.affiliation ?? null,
      notes: g.notes ?? null,
      currentSeat: seat
        ? {
            tableId: seat.tableId,
            tableLabel: table?.label ?? seat.tableId,
            seatIndex: seat.index,
            locked: false,
          }
        : null,
    };
  });

  const unseatedGuests = s.guests.filter((g) => !seatedGuestIds.has(g.id)).map((g) => g.id);

  const relationships = s.constraints.map((c) => ({
    guestAId: c.a,
    guestBId: c.b,
    type: c.kind === "must-sit-with" ? "must_sit_with" : "must_not_sit_with",
    reason: c.note ?? "",
  }));

  return (
    JSON.stringify(
      {
        specVersion: "1.0",
        generatedAt: new Date().toISOString(),
        event: { id: s.id, name: s.name },
        guests,
        unseatedGuests,
        tables,
        relationships,
      },
      null,
      2,
    ) + "\n"
  );
}

function renderGuestsCSV(s: SyncInput["state"]): string {
  const seatBy: Record<string, string> = {};
  for (const [seatKey, guestId] of Object.entries(s.assignments)) {
    seatBy[guestId] = seatKey;
  }
  const tableLabel = (id: string) => s.tables.find((t) => t.id === id)?.label ?? id;

  const rows: string[][] = [["id", "name", "affiliation", "notes", "table", "seat_index"]];
  for (const g of s.guests) {
    const sk = seatBy[g.id];
    let table = "";
    let seatIdx = "";
    if (sk) {
      const { tableId, index } = parseSeatKey(sk);
      table = tableLabel(tableId);
      seatIdx = String(index + 1);
    }
    rows.push([g.id, g.name, g.affiliation ?? "", g.notes ?? "", table, seatIdx]);
  }
  return rows.map((r) => r.map(csvCell).join(",")).join("\r\n") + "\r\n";
}

function renderTablesMD(s: SyncInput["state"]): string {
  const guestById = new Map(s.guests.map((g) => [g.id, g]));
  const lines: string[] = [
    `# ${s.name} — Tables`,
    "",
    `_Generated by Centerpeace at ${new Date().toISOString()}._`,
    "",
  ];
  for (const t of s.tables) {
    const filled = Array.from({ length: t.capacity }, (_, i) => s.assignments[`${t.id}:${i}`])
      .filter(Boolean).length;
    lines.push(`## ${t.label}  \`(${filled}/${t.capacity})\``);
    lines.push("");
    for (let i = 0; i < t.capacity; i++) {
      const gid = s.assignments[`${t.id}:${i}`];
      const g = gid ? guestById.get(gid) : undefined;
      lines.push(
        g
          ? `- Seat ${i + 1}: **${g.name}**${g.affiliation ? ` — ${g.affiliation}` : ""}`
          : `- Seat ${i + 1}: _(empty)_`,
      );
    }
    lines.push("");
  }
  return lines.join("\n");
}

function renderConstraintsMD(s: SyncInput["state"]): string {
  const guestById = new Map(s.guests.map((g) => [g.id, g]));
  const lines: string[] = [
    `# ${s.name} — Constraints`,
    "",
    `_Generated by Centerpeace at ${new Date().toISOString()}._`,
    "",
  ];
  if (s.constraints.length === 0) {
    lines.push("_No constraints defined yet._");
    return lines.join("\n");
  }

  const must = s.constraints.filter((c) => c.kind === "must-sit-with");
  const mustNot = s.constraints.filter((c) => c.kind === "must-not-sit-with");

  if (must.length) {
    lines.push("## Must sit together");
    lines.push("");
    for (const c of must) {
      const a = guestById.get(c.a)?.name ?? c.a;
      const b = guestById.get(c.b)?.name ?? c.b;
      lines.push(`- **${a}** + **${b}**${c.note ? ` — ${c.note}` : ""}`);
    }
    lines.push("");
  }
  if (mustNot.length) {
    lines.push("## Must NOT sit together");
    lines.push("");
    for (const c of mustNot) {
      const a = guestById.get(c.a)?.name ?? c.a;
      const b = guestById.get(c.b)?.name ?? c.b;
      lines.push(`- **${a}** ≠ **${b}**${c.note ? ` — ${c.note}` : ""}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

function csvCell(val: string): string {
  if (/[",\r\n]/.test(val)) return `"${val.replace(/"/g, '""')}"`;
  return val;
}
